control_port: 51881
graph_input: "graph_input1"
graph_output: "graph_output1"

node {
  name: "demux_node"
  calculator: "stream_demux"
  graph_input: "graph_input1"
  output_stream: "packetstream1"
  output_stream: "video_info_side_packet_demux"
  node_options: {
    [type.googleapis.com/aup.avaf.StreamMuxOptions]: {
      demux: {
        rtsp_transport: "tcp"  
        iframe_extract: false
        auto_reconnect: true
      }
    }
  }
}

node {
  name: "decode_node"
  calculator: "v205_dec"
  input_stream: "packetstream1"
  input_stream: "video_info_side_packet_demux"
  output_stream: "imgStream1080p"
  output_stream: "video_stream_info_decode"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoCodecOptions]: {
      dec: {
        name: "v205_dec_h2645"
        ow: 1920
        oh: 1080
        opixfmt: PIXFMT_BGR24
        queue_size: 12
        low_latency: false
      }
    }
  }
}


node {
  name: "classifier"
  calculator: "vehicle_classificaiton"
  input_stream: "imgStream1080p"
  #input_stream: "detectionsStream"
  output_stream: "imgStream1080p_class"
  #ml_model_kernel_name: "vehicle_make_resnet18_pt"
  node_options: {
    [type.googleapis.com/VehicleClassificationOptions]: {
      kernel_name: "vehicle_make_resnet18_pt"
      use_detections: false
      print_results: true
      box_thickness: 5
    }
  }
}


node {
  name: "vfilter_node"
  calculator: "ff_vfilter"
  vendor: "Aupera"
  input_stream: "imgStream1080p_class"
  input_stream: "video_stream_info_decode"
  output_stream: "image_stream_vfilter_node"
  output_stream: "video_stream_info_vfilter_node"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoFilterOptions]: {
      roi_x: 0
      roi_y: 0
      roi_w: 0
      roi_h: 0
      opixfmt: PIXFMT_I420
      ow: 1280
      oh: 720
      ofps: 20
    }
  }
}

node {
  name: "encode_node"
  calculator: "x86_enc"
  vendor: "Aupera"
  input_stream: "image_stream_vfilter_node"
  input_stream: "video_stream_info_vfilter_node"
  output_stream: "packet_stream_encode_node"
  output_stream: "codec_context_stream"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoCodecOptions]: {
      enc: {
        type: MPEG4
        w: 0
        h: 0
        #  fps: 20
      }
    }
  }
}

node {
  name: "mux_node"
  calculator: "stream_mux"
  vendor: "Aupera"
  graph_output: "graph_output1"
  input_stream: "packet_stream_encode_node"
  input_stream: "codec_context_stream"
  node_options: {
    [type.googleapis.com/aup.avaf.StreamMuxOptions]: {
     mux: {
       rtsp_transport: "tcp"
       auto_reconnect: true
     }
    }
  }
}
