CALCULATOR = box_hfnet
VENDOR = customvendor
WARNFLAGS += -Wno-unused-parameter
include VERSION.mk

OBJS = hfnet.o
LDLIBS += -lvitis_ai_library-math -lvitis_ai_library-dpu_task

include /opt/aupera/Calculator.mk
