control_port: 51881
graph_output: "graph_output1"


node {
  name: "usb_cam"
  calculator: "video_source"
  output_stream: "image_stream_decode"
  output_stream: "video_stream_info_decode"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoSourceOptions]: {
    }
  }
}



node {
  name: "detector"
  calculator: "box_detector"
  input_stream: "image_stream_decode"
  output_stream: "detections_stream"
  output_stream: "detect_interval"
  ml_model_kernel_name: "yolov3_voc"
  node_options: {
    [type.googleapis.com/aup.avaf.BoxDetectorOptions]: {
      detect_interval: 1
      detector_type: "YoloV3"
      need_preprocess: true
      log_performance: false
      run_on_letterboxed_img: false
      batch_size: 1
      return_frames_inorder: true 
      batch_collection_timeout_ms: 0
      ignore_black_frames: false
      max_detection_lib_q_size: 30
      total_classes: 20
      default_confidence_threshold: 0.3
    }
  }
}


node {
  name: "classifier"
  calculator: "box_classifier"
  input_stream: "detections_stream"
  input_stream: "image_stream_decode"
  output_stream: "classification_stream"
  ml_model_kernel_name: "resnet18"
  node_options: {
    [type.googleapis.com/aup.avaf.BoxClassifierOptions]: {
      classifier_type: "General"
      need_preprocess: true
      run_on_letterboxed_img: false
      batch_size: 8
      return_in_order: true
      classification_threads: 1
      batch_collection_timeout_ms: 0
      use_detections: true
      log_performance: false
      max_classification_lib_q_size: 200
    }
  }
}


node {
  name: "visualizer"
  calculator: "box_visualizer"
  input_stream: "classification_stream"
  input_stream: "image_stream_decode"
  output_stream: "image_stream_viz"
  stream_sync: {
    drop_strategy: DROP_INCOMPLETE_PACKETS
    timeout_ms: 5000
  }
  node_options: {
    [type.googleapis.com/aup.avaf.BoxVisualizerOptions] {
      input_type: INPUT_TYPE_CLASSIFICATION
      label_name_file: "/opt/aupera/avas/etc/default_imagenet_classification.labels"
      text_color: {
        r: 255
        g: 0
        b: 0
      }
      box_color: {
        r: 255
        g: 0
        b: 0
      }
      text_offset: {
        x: 0
        y: 0
      }
      box_thickness: 5
      font_thickness: 4
      font_scale: 1.2
      font: 0
      line_type: 0
    }
  }
}


node {
  name: "vfilter_node"
  calculator: "ff_vfilter"
  input_stream: "image_stream_viz"
  input_stream: "video_stream_info_decode"
  output_stream: "image_stream_vfilter"
  output_stream: "video_stream_info_vfilter"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoFilterOptions]: {
      roi_x: 0
      roi_y: 0
      roi_w: 0
      roi_h: 0
      opixfmt: PIXFMT_I420
      ow: 960
      oh: 540
      ofps: 12
    }
  }
}


node {
  name: "encode_node"
  calculator: "x86_enc"
  vendor: "Aupera"
  input_stream: "image_stream_vfilter"
  input_stream: "video_stream_info_vfilter"
  output_stream: "packet_stream_encode"
  output_stream: "codec_context_stream"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoCodecOptions]: {
     enc: {
       codec_type: CODEC_TYPE_H264
       fps: 12
       bitrate: 100
     }
    }
  }
}


node {
  name: "mux_node"
  calculator: "stream_mux"
  input_stream: "packet_stream_encode"
  input_stream: "codec_context_stream"
  graph_output: "graph_output1"
  node_options: {
    [type.googleapis.com/aup.avaf.StreamMuxOptions]: {
     mux: {
       rtsp_transport: "tcp"
       auto_reconnect: true
     }
    }
  }
}