control_port: 51881

node {
  name: "usb_cam"
  calculator: "video_source"
  output_stream: "image_stream_bgr"
  output_stream: "bgr_infopacket"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoSourceOptions]: {
    }
  }
}

node {
  name: "detector"
  calculator: "box_detector"
  input_stream: "image_stream_bgr"
  output_stream: "detections_stream"
  output_stream: "detect_interval"
  ml_model_kernel_name: "ssd_pedestrian_pruned_0_97"
  node_options: {
    [type.googleapis.com/aup.avaf.BoxDetectorOptions]: {
      detect_interval: 1
      detector_type: "SSD"
      need_preprocess: true
      log_performance: false
      run_on_letterboxed_img: false
      batch_size: 1
      return_frames_inorder: true 
      batch_collection_timeout_ms: 0
      ignore_black_frames: false
      max_detection_lib_q_size: 30
      total_classes: 2
      default_confidence_threshold: 0.55
    }
  }
}

node {
  name: "landmark"
  calculator: "landmark_predictor"
  input_stream: "detections_stream"
  input_stream: "image_stream_bgr"
  output_stream: "landmark_stream"
  stream_sync: {
    drop_strategy: DROP_INCOMPLETE_PACKETS
    timeout_ms: 5000
  }
  ml_model_kernel_name: "movenet_ntd_pt"
  node_options: {
    [type.googleapis.com/aup.avaf.LandmarkPredictorOptions]: {
        landmark_predictor_type: "Movenet"
        use_detections: true
        need_preprocess: true
        log_performance: true
        run_on_letterboxed_img: false
        batch_size: 3
        force_batch_size: false
        return_frames_inorder: true
        landmark_prediction_threads: 2
        batch_collection_timeout_ms: 0
        max_landmark_prediction_lib_q_size: 30
    }
  }
}

node {
  name: "visualizer1"
  calculator: "box_visualizer"
  input_stream: "landmark_stream"
  input_stream: "image_stream_nv12"
  output_stream: "image_stream_nv12_viz"
  node_options: {
    [type.googleapis.com/aup.avaf.BoxVisualizerOptions] {
      input_type: INPUT_TYPE_LANDMARK
      connect_landmarks: true
      arm_raise_check: "" 
      apply_filter_on_landmarks: "hat"
    }
  }
}

node {
  calculator: "video_sink"
  name: "sink"
  input_stream: "image_stream_nv12_viz"
  input_stream: "nv12_infopacket"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoSinkOptions]: {
      codec_type: CODEC_TYPE_H264
      bframes: 0
      gop_size: 60
      gop_mode: "low-latency-P"
      bitrate: 3000
      rc_mode: "Low Latency"
      path: "rtsp://vmss.auperatechnologies.com:554/usb-som-out-your-name"
    }
  }
}