control_port: 51881
graph_input: "inStream1"

node {
  name: "demux_node"
  calculator: "stream_demux"
  graph_input: "inStream1"
  output_stream: "packetstream1"
  output_stream: "video_info_side_packet_demux"
  node_options: {
    [type.googleapis.com/aup.avaf.StreamMuxOptions]: {
      demux: {
        rtsp_transport: "tcp"  
        iframe_extract: false
        auto_reconnect: true
      }
    }
  }
}

node {
  name: "decode_node"
  calculator: "x86_dec"
  input_stream: "packetstream1"
  input_stream: "video_info_side_packet_demux"
  output_stream: "imgStream1080p"
  output_stream: "decode_vid_info_side_packet"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoCodecOptions]: {
      dec: {
        name: "x86_dec_h2645"  
        ow: 1920
        oh: 1080
        opixfmt: PIXFMT_BGR24
        queue_size: 12
        low_latency: false
      }
    }
  }
}

node {
  name: "detector"
  calculator: "box_detector"
  input_stream: "imgStream1080p"
  ml_model_kernel_name: "RESNET18SSD_ITER90000_PRIVATE_FINAL501IMAGES_ADDED_07JUNE2021_CROWD_FLOW_PERSON_HEAD"
  node_options: {
    [type.googleapis.com/aup.avaf.BoxDetectorOptions]: {
      detect_interval: 1
      detector_type: "SSD"
      need_preprocess: true
      log_performance: false
      run_on_letterboxed_img: false
      batch_size: 1
      return_frames_inorder: true 
      batch_collection_timeout_ms: 0
      ignore_black_frames: false
      max_detection_lib_q_size: 30
      mean: {
        r: 125.319099
        g: 123.484794
        b: 120.935805
      }
      scale: {
        ch1: 1
        ch2: 1
        ch3: 1
      }
      label_confidence: {
        label: 2
        confidence: 0.5
      }
      inter_class_nms: {
        labels: 2
        threshold: 0.5
      }
    }
  }
}
