control_port: 51881
graph_input: "graph_input"
graph_output: "graph_output"

node {
  calculator: "video_source"
  name: "source"
  graph_input: "graph_input"
  output_stream: "image_stream_bgr"
  output_stream: "bgr_infopacket"
  output_stream: "image_stream_nv12"
  output_stream: "nv12_infopacket"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoSourceOptions]: {
      # path: "rtsp://vmss.auperatechnologies.com:554/car"
    }
  }
}

node {
  calculator: "video_sink"
  name: "sink"
  input_stream: "image_stream_nv12"
  input_stream: "nv12_infopacket"
  graph_output: "graph_output"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoSinkOptions]: {
      codec_type: CODEC_TYPE_H264
      bframes: 0
      gop_size: 60
      gop_mode: "low-latency-P"
      bitrate: 3000
      rc_mode: "Low Latency"
    }
  }
}