# The recommended video for this pipeline is crowd.

control_port: 51881
task_id: "DEFAULT"

node {
  calculator: "video_source"
  name: "source"
  output_stream: "image_stream_bgr"
  output_stream: "bgr_infopacket"
  output_stream: "image_stream_nv12"
  output_stream: "nv12_infopacket"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoSourceOptions]: {
      path: "rtsp://vmss.auperatechnologies.com:554/crowd"
    }
  }
}

node {
  name: "detector"
  calculator: "box_detector"
  input_stream: "image_stream_bgr"
  output_stream: "detections_stream"
  output_stream: "detect_interval"
  ml_model_kernel_name: "ssd_pedestrian_pruned_0_97"
  node_options: {
    [type.googleapis.com/aup.avaf.BoxDetectorOptions]: {
      detect_interval: 1
      detector_type: "SSD"
      need_preprocess: true
      log_performance: false
      run_on_letterboxed_img: false
      batch_size: 1
      return_frames_inorder: true 
      batch_collection_timeout_ms: 0
      ignore_black_frames: false
      max_detection_lib_q_size: 30
      label_confidence: {
        label: 0
        confidence: 0.0
      }
      label_confidence: {
        label: 1
        confidence: 0.55
      }
    }
  }
}

node {
  name: "tracker"
  calculator: "box_tracker"
  input_stream: "detections_stream"
  input_stream: "detect_interval"
  output_stream: "tracks_stream"
  node_options: {
    [type.googleapis.com/aup.avaf.BoxTrackerOptions]: {
      max_keep_alive: 5
      min_hits: 1
      affinity_threshold: 0.008  
      shape_weight: 1
      position_weight: 1
      appearance_weight: 1
      shape_dist_max: 1
      position_dist_max: 1
      use_exp_cost: true
      tracker_type: "SORT++"
      min_object_area_th: 200
    }
  }
}

node {
  name: "crowd_flow"
  calculator: "apl_crowd_flow"
  input_stream: "image_stream_nv12"
  input_stream: "nv12_infopacket"
  input_stream: "video_stream_info_demux"
  input_stream: "detect_interval"
  output_stream: "crowd_flow_notification"
  output_stream: "image_stream_crowd_flow"
  stream_sync: {
    drop_strategy: DROP_INCOMPLETE_PACKETS
    timeout_ms: 5000
  }
  node_options: {
    [type.googleapis.com/aup.avaf.AplCrowdFlowOptions]: {
      update_interval_seconds: 30
      initial_entering_count: 0
      initial_exiting_count: 0
      max_allowed_borders: 10
      
      common_fields: {
        max_file_cache: 100
        max_cluster_size: 100
        debug: true
        draw: true
        
        border: {
          p1: {
            x: 0
            y: 900
            
          }
          p2: {
            x: 1920
            y: 900
          }
          threshold: 0.055
        }
      }
    }
  }
}

node {
  calculator: "video_sink"
  name: "sink"
  input_stream: "image_stream_crowd_flow"
  input_stream: "nv12_infopacket"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoSinkOptions]: {
      codec_type: CODEC_TYPE_H264
      bframes: 0
      gop_size: 60
      gop_mode: "low-latency-P"
      bitrate: 3000
      rc_mode: "Low Latency"
      path: "rtsp://vmss.auperatechnologies.com:554/crowd-som-out-your-name"
    }
  }
}

node {
  name: "sms_notification"
  calculator: "notification_message"
  input_stream: "crowd_flow_notification"
  node_options: {
    [type.googleapis.com/aup.avaf.NotificationMessageOptions]: {
      message_type: SMS
      sender: "1xxxxxxxxxxx"
      receiver: ["1xxxxxxxxxxx"]
      notification_q_size: 2
      sender_username: "xxxxxxxxxxxxxxxxxxxxx"
      sender_password: "xxxxxxxxxxxxxxxxxxxxx"
      server_url: "https://api.twilio.com/2010-04-01/Accounts/<sender_username>/Messages.json"
      trigger: {
        trigger_type: JQ
        trigger_consecutive_packet: 3
        jq_query_string: "'select(.total_persons_entering > 10 and .interval_persons_entering % 2 == 1)'"
        notification_title: "sms_notification_test"
        notification_body: "xxxxxxxxxxxxxxxxxx"
      }
    }
  }
}