control_port: 51881

node {
  calculator: "video_source"
  name: "source"
  output_stream: "image_stream_bgr"
  output_stream: "bgr_infopacket"
  output_stream: "image_stream_nv12"
  output_stream: "nv12_infopacket"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoSourceOptions]: {
      path: "<!! input path goes here !!>"
    }
  }
}

node {
  name: "detector"
  calculator: "box_detector"
  input_stream: "image_stream_bgr"
  output_stream: "detections_stream"
  output_stream: "detect_interval"
  ml_model_kernel_name: "densebox_320_320"
  node_options: {
    [type.googleapis.com/aup.avaf.BoxDetectorOptions]: {
      detect_interval: 1
      detector_type: "FaceDetectDenseBox"
      need_preprocess: true
      log_performance: false
      run_on_letterboxed_img: false
      batch_size: 1
      return_frames_inorder: true 
      batch_collection_timeout_ms: 0
      ignore_black_frames: false
      max_detection_lib_q_size: 30
      total_classes: 2
      default_confidence_threshold: 0.9
    }
  }
}


node {
  name: "visualizer_nv12"
  calculator: "box_visualizer"
  input_stream: "detections_stream"
  input_stream: "image_stream_nv12"
  output_stream: "image_stream_nv12_viz"
  stream_sync: {
    drop_strategy: DROP_INCOMPLETE_PACKETS
    timeout_ms: 5000
  }
  node_options: {
    [type.googleapis.com/aup.avaf.BoxVisualizerOptions]: {
      text_color: {
        r: 255
        g: 0
        b: 0
      }
      box_color: {
        r: 255
        g: 0
        b: 0
      }
      text_offset: {
        x: 0
        y: 0
      }
      font: 1
      line_type: 0
      box_thickness: 5
      text_size: 2
      render_on_nv12: true
      ttf_file_path_for_nv12: "./"
      input_type: 0
    }
  }
}

node {
  calculator: "video_sink"
  name: "sink"
  input_stream: "image_stream_nv12_viz"
  input_stream: "nv12_infopacket"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoSinkOptions]: {
      codec_type: CODEC_TYPE_H264
      bframes: 0
      gop_size: 60
      gop_mode: "low-latency-P"
      bitrate: 3000
      rc_mode: "Low Latency"
      path: "<!! output path goes here !!>"
    }
  }
}
