# The recommended video for this pipeline is retail.

control_port: 51883

graph_input: "graph_input"

node {
  name: "demux_node"
  calculator: "stream_demux"
  graph_input: "graph_input"
  output_stream: "packet_stream"
  output_stream: "video_info_side_packet_demux"
  node_options: {
    [type.googleapis.com/aup.avaf.StreamMuxOptions]: {
      demux: {
        rtsp_transport: "tcp"  
        iframe_extract: false
        auto_reconnect: true
      }
    }
  }
}
node {
  name: "decode_node"
  calculator: "x86_dec"
  input_stream: "packet_stream"
  input_stream: "video_info_side_packet_demux"
  output_stream: "image_stream"
  output_stream: "video_info_side_packet_decode"
  node_options: {
    [type.googleapis.com/aup.avaf.VideoCodecOptions]: {
      dec: {
        ow: 1920
        oh: 1080
        opixfmt: PIXFMT_BGR24
        queue_size: 12
        low_latency: false
      }
    }
  }
}

node {
  name: "subgraph"
  calculator: "subgraph"
  input_stream: "image_stream"
  output_stream: "detection_stream"
  node_options: {
    [type.googleapis.com/aup.avaf.SubgraphOptions]: {
      input_attrs: {
        type: PACKET_TYPE_IMAGE
        pool_sz: 2
        entry_sz_kb: 6080
      }
      output_attrs: {
        type: PACKET_TYPE_DETECTIONS
        pool_sz: 2
        entry_sz_kb: 64
      }
      subgraph_config: {
        node {
          name: "host_source_image_stream"
          calculator: "host_source"
          output_stream: "image_stream"
          node_options: {
            [type.googleapis.com/aup.avaf.HostSourceSinkOptions]: {
              index: 0
            }
          }
        }
        node {
          name: "detector"
          calculator: "box_detector"
          input_stream: "image_stream"
          output_stream: "detection_stream"
          output_stream: "detect_interval_side_packet_dangling"
          ml_model_kernel_name: "dk_tiny-yolov3_416_416_5.46G_2.0"      
          node_options: {
            [type.googleapis.com/aup.avaf.BoxDetectorOptions]: {
              detect_interval: 1
              detector_type: "TinyYolo"
              need_preprocess: true
              log_performance: false
              run_on_letterboxed_img: false
              batch_size: 1
              return_frames_inorder: true 
              batch_collection_timeout_ms: 0
              ignore_black_frames: false
              max_detection_lib_q_size: 30
              label_confidence: {
                label: 0
                confidence: 0.5
              }
              label_confidence: {
                label: 1
                confidence: 0.5
              }
              label_confidence: {
                label: 2
                confidence: 0.5
              }
              label_confidence: {
                label: 3
                confidence: 0.5
              }
              label_confidence: {
                label: 4
                confidence: 0.5
              }
              label_confidence: {
                label: 5
                confidence: 0.5
              }
              label_confidence: {
                label: 6
                confidence: 0.5
              }
              label_confidence: {
                label: 7
                confidence: 0.5
              }
              label_confidence: {
                label: 8
                confidence: 0.5
              }
              label_confidence: {
                label: 9
                confidence: 0.1
              }
            }
          }
        }
        node {
          name: "host_sink_detections"
          calculator: "host_sink"
          input_stream: "detection_stream"
          node_options: {
            [type.googleapis.com/aup.avaf.HostSourceSinkOptions]: {
              index: 0
            }
          }
        }
      }
    }
  }
}

node {
  name: "to_json"
  calculator: "to_json"
  input_stream: "detection_stream"
  output_stream: "json_stream"
  node_options: {
    [type.googleapis.com/aup.avaf.ToJsonOptions]: {
      label_name_file: "/opt/aupera/avas/label_files/dk_tiny_yolo.txt"
      network: "tinyyolov3"
      input_type: PACKET_TYPE_DETECTIONS
    }
  }
}


node {
  name: "notification_mongo_node"
  calculator: "notification_mongo"
  input_stream: "json_stream"
  node_options: {
    [type.googleapis.com/aup.avaf.NotificationMongoOptions]: {
      mongodb_address: "mongodb://127.0.0.1:27019"
      database_name: "test_db"
      collection_name: "test_collection"
      notification_q_size: 1
    }
  }
}


console_logging_filter: {
  enable_all: true
}
file_logging_filter: {
  enable_all: true
}
