CALCULATOR = to_json
VENDOR = aupera
include VERSION.mk

CXXFLAGS += -I../box_common -I../../dependencies/include
LDFLAGS += -L../box_common -L../../dependencies/lib
include ../calculator_common/Calculator.mk